micronaut:
  application:
    name: keyManager

datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
    dialect: ${JDBC_DIALECT:H2}

#Definindo configuracoes basicas do jpa.
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

client:
  itau:
    contas: ${ITAU_CONTAS_URL:`http://localhost:9091/api/v1`}
  bancoCentral:
    pix: ${BACEN_PIX_URL:`http://localhost:8082/api/v1/pix`}